List<Map> data = [
  {
    'id' : 1,
    'name': "Sun",
    'image' : "assets/images/sun.png",
    'content' : "The Sun is a 4.5 billion-year-old yellow dwarf star – a hot glowing ball of hydrogen and helium – at the center of our solar system.",
    'distanceToSun' : "0 million km",
    'distanceToEarth' : "147.67 million km",
  },
  {
    'id' : 2,
    'name' : "Mercury",
    'image' : "assets/images/Mercury.png",
    'content' : "Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun's planets.",
    'distanceToSun' : "47.919 million km",
    'distanceToEarth' : "162.75 million km",
  },
  {
    'id' : 3,
    'name':"Venus",
    'image' : "assets/images/Venus.png",
    'content' : " Venus is the second planet from the Sun and is Earth’s closest planetary neighbor. It’s one of the four inner, terrestrial (or rocky) planets, and it’s often called Earth’s twin because it’s similar in size and density. These are not identical twins, however – there are radical differences between the two worlds.",
    'distanceToSun' : "108 million km",
    'distanceToEarth' : " 0.7 times million km",
  },
  {
    'id' : 4,
    'name' : "Earth",
    'image' : "assets/images/Earth.png",
    'content' : "Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface.",
    'distanceToSun' : "150 million km",
    'distanceToEarth' : "0 million km",
  },
  {
    'id' : 5,
    'name' : "Moon",
    'image' : "assets/images/moon.png",
    'content' : "The Moon is Earth's only natural satellite. It is about one-quarter of Earth in diameter (comparable to the width of Australia).In the Solar System the Moon is the fifth largest satellite",
    'distanceToSun' : "150 million km",
    'distanceToEarth' : "384,400  million km",
  },
  {
    'id' : 6,
    'name' : "Mars",
    'image' : "assets/images/Mars.png",
    'content' : "Mars is the fourth planet from the Sun – a dusty, cold, desert world with a very thin atmosphere. Mars is also a dynamic planet with seasons, polar ice caps, canyons, extinct volcanoes, and evidence that it was even more active in the past.",
    'distanceToSun' : "228 million km",
    'distanceToEarth' : "54.6 million km",
  },
  {
    'id' : 7,
    'name' : "Jupiter",
    'image' : "assets/images/Jupiter.png",
    'content' : "Jupiter is the fifth planet from our Sun and is, by far, the largest planet in the solar system – more than twice as massive as all the other planets combined.",
    'distanceToSun' : "778 million km",
    'distanceToEarth' : "778 million km",
  },
  {
    'id' : 8,
    'name' : "Saturn",
    'image' : "assets/images/Saturn.png",
    'content' : "Saturn is the sixth planet from the Sun and the second-largest planet in our solar system.",
    'distanceToSun' : "1.4 billion km",
    'distanceToEarth' : "1.2 billion km",
  },
  {
    'id' : 9,
    'name' : "Uranus",
    'image' : "assets/images/Uranus.png",
    'content' : "Uranus is the seventh planet fromhe Sun, and has the third-largest diameter in our solar system.",
    'distanceToSun' : "2.9 billion km",
    'distanceToEarth' : "2.6 billion km",
  },
  {
    'id' : 10,
    'name' : "Neptune",
    'image' : "assets/images/Neptune.png",
    'content' : "More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye and the first predicted by mathematics before its discovery. ",
    'distanceToSun' : "4.5 billion km",
    'distanceToEarth' : "4.3 billion km",
  },
  {
    'id' : 11,
    'name' : "Pluto",
    'image' : "assets/images/pluto.png",
    'content' : "Pluto is a dwarf planet in the Kuiper Belt, a donut-shaped region of icy bodies beyond the orbit of Neptune.",
    'distanceToSun' : "5.9 billion km",
    'distanceToEarth' : "7.5 billion km",
  },

];